name: pangeo-LunchBytes_intake-esm
channels:
  - conda-forge
dependencies:
  - pangeo-notebook
  - intake-xarray
  - nb_black
  - pip
  # regridding
  - xesmf
  - cartopy # mapping
  - pip:
    - git+https://github.com/bradyrx/climpred.git
    - git+https://github.com/NCAR/intake-esm.git
    - git+https://github.com/jbusecke/cmip6_preprocessing.git
    - git+https://github.com/mathause/regionmask.git
